# Generated by Django 5.2 on 2025-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0002_todouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
