# Generated by Django 5.2 on 2025-05-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0003_alter_todouser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='assignments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='todouser',
            name='days',
            field=models.CharField(default='', max_length=100),
        ),
    ]
