# Generated by Django 5.2 on 2025-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0004_todouser_assignments_todouser_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='daysandassignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('assignments', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
