# Generated by Django 5.2 on 2025-05-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdemoapp2', '0006_arduinodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinodata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
